name: "DEV: Build & Push & Update | Discord Bot Manhole"

on:
  pull_request:
    types: [closed]
    branches:
      - develop

  workflow_dispatch:

jobs:
  build-and-push:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_image_tag.outputs.tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set image tag with short commit hash
      id: set_image_tag
      run: |
        short_sha=$(echo "${{ github.sha }}" | cut -c1-5)
        echo $short_sha
        echo tag="test-$short_sha" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/manhole_bot:${{ steps.set_image_tag.outputs.tag }}

    - name: Logout from Docker Hub
      run: docker logout

  deploy-on-target:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      tag: ${{ needs.build-and-push.outputs.tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        echo $tag
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible

    - name: Add ssh key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 2222 147.235.230.164 >> ~/.ssh/known_hosts

    - name: Disable host key checking
      run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

    - name: Deploy
      run: |
        ansible-playbook -i Ansible/inventory.yaml Ansible/dev-playbook.yaml --extra-vars "TOKEN_BOT=${{ secrets.TOKEN_BOT_TEST }} START_WITH=${{ vars.START_WITH_DEV }} tag=$tag"